CREATE DATABASE escuela;
use escuela;

CREATE TABLE USUARIO(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100)
);

CREATE TABLE PAGINA(
PAGINA_ID INT PRIMARY KEY AUTO_INCREMENT,
URL VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL
);


CREATE TABLE MENU(
MENU_ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE PAGINA_MENU(
PAGINA_MENU INT PRIMARY KEY AUTO_INCREMENT,
MENU_ID INT NOT NULL,
PAGINA_ID INT NOT NULL
);

CREATE TABLE USUARIO_ACCESO(
USUARIO_ACCESO_ID INT PRIMARY KEY AUTO_INCREMENT,
PAGINA_ID INT NOT NULL,
USUARIO_ID INT NOT NULL
);

CREATE TABLE ALUMNO(
ALUMNO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO_PATERNO VARCHAR(50) NOT NULL,
APELLIDO_MATERNO VARCHAR(50) NOT NULL,
MATRICULA VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
UPLOAD VARCHAR(50)  NULL,
USUARIO_ID INT NOT NULL,
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   
);

CREATE TABLE EMPLEADO(
MAESTRO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO_PATERNO VARCHAR(50) NOT NULL,
APELLIDO_MATERNO VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT  NULL,
USUARIO_ID INT NOT NULL,
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   
);

CREATE TABLE BLOG(
BLOG_ID INT PRIMARY KEY NOT NULL,
TITLE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
UPLOAD VARCHAR(50) NOT NULL,
USARIO_ID INT NULL,
TIPO_USUARIO_ID INT NOT NULL
);

ALTER TABLE PAGINA_MENU ADD CONSTRAINT FK_PAGINA_MENU_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID);
ALTER TABLE PAGINA_MENU ADD CONSTRAINT FK_PAGINA_MENU_PAGINA_ID FOREIGN KEY (PAGINA_ID) REFERENCES PAGINA(PAGINA_ID);
ALTER TABLE USUARIO_ACCESO ADD CONSTRAINT FK_USUARIO_ACCESO_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);
ALTER TABLE USUARIO_ACCESO ADD CONSTRAINT FK_USUARIO_ACCESO_PAGINA_ID FOREIGN KEY (PAGINA_ID) REFERENCES PAGINA(PAGINA_ID);
ALTER TABLE ALUMNO ADD CONSTRAINT FK_ALUMNO_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);
ALTER TABLE BLOG ADD CONSTRAINT FK_ESCUELA_TIPO_USUARIO_ID FOREIGN KEY (TIPO_USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);
INSERT INTO USUARIO VALUES(NULL,'Administrador','Controla todo');
INSERT INTO USUARIO VALUES(NULL,'Alumno','Alumno');

DELIMITER $$
--
-- Procedimientos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `saveEditAlumno` (IN ALUMNO_ID INT, IN NOMBRE VARCHAR(50),IN APELLIDO_P VARCHAR(50), 
                                                        IN APELLIDO_M VARCHAR(50),IN MATRICULA VARCHAR(15),
                                                        IN EMAIL VARCHAR(100), IN PASSWORD VARCHAR(100),
                                                        IN UPLOAD VARCHAR(100))  begin 
IF ALUMNO_ID =0 then 
INSERT INTO ALUMNO values(null, NOMBRE, APELLIDO_P, APELLIDO_M, MATRICULA, EMAIL, PASSWORD, UPLOAD, 3,NULL);
set ALUMNO_ID = LAST_INSERT_ID();
ELSE
UPDATE ALUMNO
	SET ALUMNO.NOMBRE = nombre,
    	ALUMNO.APELLIDO_PATERNO = ALUMNO_P,
        ALUMNO.APELLIDO_MATERNO  = ALUMNO_M,
        ALUMNO.MATRICULA  = MATRICULA,
        ALUMNO.EMAIL  = EMAIL,
        ALUMNO.UPLOAD = UPLOAD
    WHERE ALUMNO.ALUMNO_ID = ALUMNO_ID;
END IF;

END$$

DELIMITER ;